import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import { StoreProvider } from '@/store/Store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next AI Adventure',
  description: 'Generated by Arik Alexandrov',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>

      
      <body className={inter.className}>
        <Header />
        {children}
      </body>
      </StoreProvider>
    </html>
  )
}
